# Generated by Django 5.0.6 on 2024-07-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Address_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Address_2',
            new_name='address_2',
        ),
    ]
